services:
  postgres:
    image: postgres:16
    container_name: cf_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: constructflow
      POSTGRES_PASSWORD: CHANGE_THIS_DB_PASSWORD
      POSTGRES_DB: constructflow
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:latest
    container_name: cf_minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: CHANGE_THIS_MINIO_PASSWORD
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
  pg_data:
  minio_data:
